name: ngon_mang_di
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+7

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  go_router: ^15.1.1
  firebase_core: ^3.13.0
  firebase_messaging: ^15.2.5
  firebase_analytics: ^11.4.5
  flutter_local_notifications: ^19.2.0
  intl: ^0.20.2
  flutter_dotenv: ^5.2.1
  supabase_flutter: ^2.0.0
  provider: ^6.1.2
  shared_preferences: ^2.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.3

flutter:
  uses-material-design: true
  assets:


#      images
    - assets/images/
    - assets/images/baby/
    - assets/images/cake/
    - assets/images/office/
    - assets/images/confectionery/


#    json
    - assets/recipes.json
    - assets/office.json
    - assets/cake.json
    - assets/baby.json
    - assets/confectionery.json
    - assets/highlight_recipes.json
    - assets/recipe_detail.json

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/logo.png"
