// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBArE2sVpLjPuU2YGwL13WexMgwZiFN-Qs',
    appId: '1:709378192552:web:6f7838f36b4c573fb67e9d',
    messagingSenderId: '709378192552',
    projectId: 'ngonmangdi',
    authDomain: 'ngonmangdi.firebaseapp.com',
    storageBucket: 'ngonmangdi.firebasestorage.app',
    measurementId: 'G-WEK5D98MWY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDMWnfyusvlqKuilzW_P_QjWV3klFVnuu0',
    appId: '1:709378192552:android:65385185ccae5b52b67e9d',
    messagingSenderId: '709378192552',
    projectId: 'ngonmangdi',
    storageBucket: 'ngonmangdi.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBIiY6YF_TIwL307VjzO_-mHR3evkynfDk',
    appId: '1:709378192552:ios:d4ffcf46d4ec3506b67e9d',
    messagingSenderId: '709378192552',
    projectId: 'ngonmangdi',
    storageBucket: 'ngonmangdi.firebasestorage.app',
    iosBundleId: 'com.example.ngonMangDi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBIiY6YF_TIwL307VjzO_-mHR3evkynfDk',
    appId: '1:709378192552:ios:d4ffcf46d4ec3506b67e9d',
    messagingSenderId: '709378192552',
    projectId: 'ngonmangdi',
    storageBucket: 'ngonmangdi.firebasestorage.app',
    iosBundleId: 'com.example.ngonMangDi',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBArE2sVpLjPuU2YGwL13WexMgwZiFN-Qs',
    appId: '1:709378192552:web:5aaa33370833fee1b67e9d',
    messagingSenderId: '709378192552',
    projectId: 'ngonmangdi',
    authDomain: 'ngonmangdi.firebaseapp.com',
    storageBucket: 'ngonmangdi.firebasestorage.app',
    measurementId: 'G-3XCP5JMRP2',
  );
}
